//alert ("Hola Mundo");
//const nombre =prompt("Ingrese el nombre");
//document.querySelector(".contenido").innerHTML=`${nombre} Esta trabajando con Java`
console.log("Hola mundo desde consola")
let numero1=prompt(`ingrese el valor numerico`)
let numero2=prompt(`Ingrese numero 2`)
console.log(numero1);
console.log(numero2);
//suma de valores desde la consola
console.log("la suma de lso valores:" +(parseInt(numero1)+ parseInt(numero2)))